name: Python package

on:
  push:
    branches: [port-forwarding]
  pull_request:
    branches: [port-forwarding]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create logs directory
        run: mkdir -p ddpui/logs
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
      - name: Add remote host key to known_hosts
        run: ssh-keyscan ${{ secrets.SERVERIP }} >> ~/.ssh/known_hosts
      - name: Set up port forwarding via SSH
        run: |
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh -L 8080:localhost:8080 ddp@65.2.5.51 -f -N
      - name: Check if server is running
        run: curl http://localhost:8080/proxy/blocks/airbyte/server/airbyte1
      - name: Check prefect tests
        run: pytest ddpui/tests/unit_integration_tests/test_prefect_service.py
      - name: Test with pytest
        env:
          AIRBYTE_SERVER_HOST: localhost
          AIRBYTE_SERVER_PORT: 8000
          AIRBYTE_SERVER_APIVER: v1
          AIRBYTE_API_TOKEN: ${{ secrets.AIRBYTE_API_TOKEN }}
          DBHOST: ${{ secrets.DBHOST }}
          DBNAME: ${{ secrets.DBNAME }}
          DBUSER: ${{ secrets.DBUSER }}
          DBPASSWORD: ${{ secrets.DBPASSWORD }}
          PREFECT_PROXY_API_URL: http://localhost:8080
        run: |
          coverage run -m pytest --ignore=ddpui/tests/integration_tests
          coverage report --fail-under=70
          coverage xml
          cd ddpui/tests
          pytest --cov --ignore=integration_tests
      - name: Check coverage percentage
        run: |
          coverage_percentage=$(coverage report --show-missing | tail -n 1 | awk '{print $4}')
          if (( $(echo "$coverage_percentage < 70" | bc -l) )); then
            echo "Coverage percentage is below 70%"
            exit 1
          fi
      - name: Upload coverage reports to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
