name: Python package

on:
  push:
    branches: [automate_tests]
  pull_request:
    branches: [automate_tests]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create logs directory
        run: mkdir -p ddpui/logs
      - name: Set environment variables
        run: |
          echo "AIRBYTE_SERVER_HOST=${{ secrets.AIRBYTE_SERVER_HOST }}" >> $GITHUB_ENV
          echo "AIRBYTE_SERVER_PORT=${{ secrets.AIRBYTE_SERVER_PORT }}" >> $GITHUB_ENV
          echo "AIRBYTE_SERVER_APIVER=${{ secrets.AIRBYTE_SERVER_APIVER }}" >> $GITHUB_ENV
          echo "AIRBYTE_API_TOKEN=${{ secrets.AIRBYTE_API_TOKEN }}" >> $GITHUB_ENV
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pip install pytest
          pip install pytest-cov
          pytest ddpui/tests/unit_integration_tests/test_airbyte_service_unit.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
